package com.example.springbootdemo07.mapper;

import com.example.springbootdemo07.pojo.TbBook;
import org.mapstruct.Mapper;

import java.util.List;
@Mapper
public interface TbBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbg.generated Sun Apr 30 20:07:59 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbg.generated Sun Apr 30 20:07:59 CST 2023
     */
    int insert(TbBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbg.generated Sun Apr 30 20:07:59 CST 2023
     */
    TbBook selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbg.generated Sun Apr 30 20:07:59 CST 2023
     */
    List<TbBook> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbg.generated Sun Apr 30 20:07:59 CST 2023
     */
    int updateByPrimaryKey(TbBook record);



}